### PR TITLE
Xen-API Java SDK: fix the build (reintroduce 2.20 API version definition)

### PR DESCRIPTION
**Pull request by edwintorok**
The Java SDK was failing to build due to 29f844cc6:
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.11.0:compile (default-compile) on project xen-api: Compilation failure
[ERROR] /home/edvint/koji/toolstack-dev2/xapi.spec/scm/_build/install/default/xapi/sdk/java/xen-api/src/main/java/com/xensource/xenapi/APIVersion.java:[63,16] cannot find symbol
[ERROR]   symbol:   variable API_2_20
[ERROR]   location: class com.xensource.xenapi.APIVersion
[ERROR] -> [Help 1]
```

Draft PR, because I've only compile tested it, haven't tried whether the SDK actually works once built.

### CODE REVIEW

File: ocaml/idl/datamodel_types.ml [hunk 1]
```diff
@@ -334,6 +334,13 @@ let release_order_full =
     ; branding= "Citrix Hypervisor 8.2 Hotfix 2"
     ; release_date= Some "November 2020"
     }
+  ; {
+      code_name= Some "stream"
```
Comment (kc284) [inline ocaml/idl/datamodel_types.ml:338]: Could  we call this "cloud" to match the terms the UI uses internally.

Comment (edwintorok) [reply ocaml/idl/datamodel_types.ml]: Changed to `nile-preview` according to our latest discussion.

**Review by robhoes — APPROVED** [review]

**Review by kc284 — APPROVED** [review]
