### PR TITLE
CP-12901: add a notion of XenAPI "extensions"

### PR DESCRIPTION
**Pull request by djs55**
A XenAPI extension implements a single XenAPI call, outside of xapi. The extension can either be

- *declared*: represented in the data model as a message, with `forward_to` set. This is preferred since it formalises the argument types, result types, documentation strings, acceptable errors, lifecycle and ensures first-class support in the SDK
- *undeclared*: an API which isn't declared in the datamodel can still be invoked, if the implementation is found to be present at runtime.

If an *undeclared* API is created then the definition *must* still be added to the master branch, so that future builds of the SDK will include it. The useful thing is that the very same undeclared API *implementation* can be added to an older dom0 (e.g. in another RPM) and will work. Hopefully for a lot of use-cases this is better than using "plugins" (which lack SDK support and have weaker type checking).

By default extensions are placed in `/etc/xapi.d/extensions` and are executable files named after the API call (e.g. `LVHD.enable_thin_provisioning`). The calling convention is: the program is executed with the argument `--xmlrpc` and the full XenAPI XMLRPC request is sent to stdin. The program should run and print the XenAPI XMLRPC response on stdout. If the process fails (exits non-zero) then this is considered an internal error.

Note this adds a declaration for `LVHD.enable_thin_provisioning` as an example.

This relies on [xapi-project/forkexecd#9]

This needs to be merged at the same time as [xapi-project/xen-api-sdk#52]

### CODE REVIEW

**Comment by simonjbeaumont** [comment]
For the record: some of the best commit messages I've read in a while :+1: and even an example :+1::+1:

**Comment by djs55** [comment]
OK, thanks for your comments @robhoes and @simonjbeaumont. I think I've addressed everything except Rob's concern about the API bindings. I'll check whether changes are needed there.

**Comment by djs55** [comment]
```
+ ocamlfind ocamlopt -package rpclib,getopt,xmlm,xml-light2,uuid,stdext,xcp,unix,str -warn-error A -dtypes -I /output/api/datamodel -thread -I . -I .. -I /output/api/datamodel -c gen_csharp_binding.ml
File "gen_csharp_binding.ml", line 544, characters 2-859:
Error: Some record fields are undefined: msg_forward_to
*** omake: 62/106 targets are up to date
*** omake: failed (2.44 sec, 6/6 scans, 10/19 rules, 31/156 digests)
*** omake: targets were not rebuilt because of errors:
   csharp/gen_csharp_binding.cmi
      depends on: csharp/gen_csharp_binding.ml
   csharp/gen_csharp_binding.cmx
      depends on: csharp/gen_csharp_binding.ml
   csharp/gen_csharp_binding.o
      depends on: csharp/gen_csharp_binding.ml
```

**Comment by djs55** [comment]
Now we have:
```
javac -cp :xmlrpc-client-3.1.jar:xmlrpc-common-3.1.jar:ws-commons-util-1.0.2.jar com/xensource/xenapi/VMPP.java
Note: ./com/xensource/xenapi/Types.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
javac -cp :xmlrpc-client-3.1.jar:xmlrpc-common-3.1.jar:ws-commons-util-1.0.2.jar com/xensource/xenapi/LVHD.java
com/xensource/xenapi/LVHD.java:75: error: cannot find symbol
        Object[] method_params = {Marshalling.toXMLRPC(session), Marshalling.toXMLRPC(this.ref), Marshalling.toXMLRPC(initialAllocation), Marshalling.toXMLRPC(allocationQuantum)};
                                                                                          ^
  symbol: variable ref
com/xensource/xenapi/LVHD.java:94: error: cannot find symbol
        Object[] method_params = {Marshalling.toXMLRPC(session), Marshalling.toXMLRPC(this.ref), Marshalling.toXMLRPC(initialAllocation), Marshalling.toXMLRPC(allocationQuantum)};
                                                                                          ^
  symbol: variable ref
2 errors
make[4]: *** [com/xensource/xenapi/LVHD.class] Error 1
```

**Comment by djs55** [comment]
OK, now this has broken:
```
Invoke-XenLVHD.cs(148,47): error CS0117: 'XenAPI.LVHD' does not contain a definition for 'get_record'
End of build at Thu Aug 20 20:22:16 UTC 2015
Deleting working dir C:\Users\Administrator\remote-ops-tmp\ropsih7u1z
make[3]: *** [/obj/XenServerPowerShell.dll] Error 1
make[2]: *** [__xen-api-sdk-build] Error 1
make[1]: *** [/local/scratch/dscott/trunk-ring3-tmp/build.hg/obj/.build-xen-api-sdk] Error 2
make[1]: Target `/local/scratch/dscott/trunk-ring3-tmp/build.hg/obj/c/.xen-api-sdk-installed.md5' not remade because of errors.
make: *** [xen-api-sdk-build] Error 2
```

File: ocaml/idl/datamodel.ml [hunk 1]
```diff
@@ -5587,6 +5590,33 @@ let storage_plugin =
...
     ()
 
+let lvhd_enable_thin_provisioning = call
+   ~name:"enable_thin_provisioning"
+   ~in_oss_since:None
+   ~in_product_since:rel_dundee
+   ~allowed_roles:_R_POOL_ADMIN
+   ~params:[
+     Ref _sr, "SR", "The LVHD SR to upgrade to being thin-provisioned.";
+     Int, "initial_allocation", "The initial amount of space to allocate to a newly-created VDI in bytes";
```
Comment (simonjbeaumont) [inline ocaml/idl/datamodel.ml]: I was just told that they want to use MB here, not bytes. :(

Comment (djs55) [inline ocaml/idl/datamodel.ml]: The XenAPI standard is bytes, not MB or MiB or KB or KiB or GB or GiB-- the
implementation will have to convert.

Standardising on bytes has saved us *loads* of problems in the past,
compared to the previous implementation...

Comment (simonjbeaumont) [inline ocaml/idl/datamodel.ml]: I think this is a good justification. One I tried to make myself but I don't have the sufficient credits.

Comment (germanop) [inline ocaml/idl/datamodel.ml]: It is not about "credits". Whatever needs to be filled by the user, given in this case we are talking about MBs or GBs, cannot be passed in bytes.
If this is an internal thing that the user cannot see, than it is fine, we can pass bytes ourselves.

What I said is that the sm-config fields related to quantum allocation and initial allocation need to be in a human-writable format: I cannot picture anyone writing down 1GB in bytes.

If the default is bytes for this call but this call accepts suffixes like MiB and GiB, than it is fine
for me, as long as we are on the same page.

Comment (djs55) [inline ocaml/idl/datamodel.ml]: The CLI will accept suffixes with no problem. (This mechanism would break
if the api itself used anything except bytes)

Comment (germanop) [inline ocaml/idl/datamodel.ml]: The original conversation was about how SM and XC agreed on passing info using the sm-config field. That field is custom (in fact we are passing fractions now) so, as long it is clear
to the user, we can decide any kind of arrangement. Given the minimum granularity for that field is above MBs, that is the reasonable choice.

I do not know how this can break any xapi model, given this field did not exist and it is a custom SM field..
